### ISSUE TITLE
Build fehlgeschlagen - no theme named 'sphinx_rtd_theme' found (missing theme.conf?)

### ISSUE THREAD

**Issue by richardjubla** [hitobito/user_documentation#34]
Ich habe gesehen, dass der aktuelle Build für das Handbuch nicht abgeschlossen werden kann. 
![image](https://github.com/hitobito/user_documentation/assets/95908537/64e769b3-90b9-47ff-827a-ce5fc79157e5)

Bei uns war dies auch der Fall und ich wäre interessiert zu wissen, weshalb und wie dies verhindert werden kann.
Meine "Lösung" für unser Handbuch: python 3.11 (anstelle von 3.12) und requirements.txt ohne Versionsangaben (entgegen der Empfehlung im Manual)

Falls nicht Hilfreich, Issue einfach schliessen.

**Comment by olibrian** [comment]
Habe unsere Konfig im dem PR https://github.com/hitobito/user_documentation/pull/42 angepasst. Als Vorlage habe ich die [Readthedocs Template](https://github.com/readthedocs/tutorial-template/) verwendet
