### ISSUE TITLE
Link nicht mehr gültig

### ISSUE THREAD

**Issue by Michael-Schaer** [hitobito/user_documentation#35]
https://github.com/hitobito/user_documentation/blob/961fb91576d24d1a12711f50cb28a3bb56be6f97/ebics.rst?plain=1#L18

Wohin sollte dieser Link zeigen?

**Comment by carlobeltrame** [comment]
Vermutlich hierhin? https://www.six-group.com/de/products-services/banking-services/payment-standardization/standards/ebics.html

**Comment by Michael-Schaer** [comment]
https://github.com/hitobito/user_documentation/pull/37
