### ISSUE TITLE
Community User Documentation

### ISSUE THREAD

**Issue by olibrian** [hitobito/user_documentation#5]
Hier eine Sammlung von User Dokumentation/Dokumente von den Community Mitgliedern:

Hitobito generische User Doku: https://hitobito.readthedocs.io/de/latest/
SBV: https://handbuch-hitobito.readthedocs.io/de/latest/
Cevi: https://wiki.cevi.ch/index.php/Cevi.DB
Jubla: http://jubla.ch/datenbank
PBS: http://info-de.scouts.ch/ oder http://info-fr.scouts.ch/ oder https://pfadi.swiss/it/midata/
Die Mitte: Wir zur Zeit noch erstellt (Mehrsprachig)

Ziel ist es diese Dokumente mindestens zu verlinken.

**Comment by carlobeltrame** [comment]
Der SBV hat auch noch die Erklärvideos: https://www.youtube.com/watch?v=-XPwxKcvS4c&list=UUjGtTWlk8_HvhjCo8eVUmvw&index=13

**Comment by richardjubla** [comment]
Das "Benutzerhandbuch" der @jubla-ch ist neu hier: https://github.com/jubla-ch/handbuch-jubladb-hitobito 
(Ein "fork" von SBV/Hitobito und wird hoffentlich in Zukunft jubla-spezifischer gepflegt)

**Comment by olibrian** [comment]
Notizen aus dem Hackathon 2023:

## Generische Doku (https://hitobito.readthedocs.io/)

* Allgemeine Doku über Hitobito ohne spezifische Anpassungen an den Wagons
* Ziel für einen Überblick was Hitobito alles kann
* Diese Doku wird gemeinsam gepflegt
* Bemerkungen oder eine Infobox falls das Modul in mehreren Wagons gross abweicht. Analog bei den Rechnungen (https://hitobito.readthedocs.io/de/latest/access_concept.html)

## Kundenspezifische Doku 
* Zielgruppe: Endbenutzer 
* Usecase spezifische Anleitung (z.b. Wie erstelle ich als Scharleiterin ein Lager)
* Gepflegt durch entsprechende Organisationen in ihren Hilfsmittel
* Verweis oder Kopie von der generische Doku möglich
