### ISSUE TITLE
readme | Link reference

### ISSUE THREAD

**Issue by sgruber94** [hitobito/user_documentation#8]
Sadly I can´t find any useful link, in the readme in this section.

`A helpful overview over the restructured syntax that we use can be found here: http://docs.sphinxdocs.com/en/latest/step-1.html`

Is this link better and more describable?
https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html

**Comment by KunoKunz** [comment]
thanks for the note. I've updated the link in the readme
